### ISSUE TITLE
I2C clock line collapsing on Raspsberry Pi

### ISSUE THREAD

**Issue by karan259** [Seeed-Studio/Grove_I2C_Motor_Driver#1]
the motor driver is very sensitive to I2C read/write if you send it anything that is not hard-coded on the firmware it crashes and takes the whole I2C bus down. This is a bit worrisome because even the GrovePi works on I2C and it also stops working if the motor driver brings the I2C bus down.

The easiest way to replicate and test it at your end would be put the logic analyzer on the I2C lines and connect the Motor Driver to the GrovePi and run this example: https://github.com/DexterInd/GrovePi/blob/master/Software/Python/grove_i2c_motor_driver/motor_example.py. After this run i2cdetect -y 1 and you'll see the I2C data line clock line collapsing

**Comment by lanselambor** [comment]
You're right, this module crashed when using i2cdetect.We'll try to fix it.

**Comment by Springwald** [comment]
Hi,

when will a fixed firmware be available?

**Comment by Springwald** [comment]
two years gone - any idea, when this bug will be fixed?

**Comment by lanselambor** [comment]
Have modified firmware code to fix i2cdetect block on raspberry pi.

Users who got this motor driver can use AVR ISP programmer mkII to burn the new firmware at `./burn firmware for Atmega8 using ISP/motor driver firmware/mega8motor_v2.hex.`

Tools:
- AVR ISP programmer mkII
- avrdude 

Upload firmware Command:
`avrdude -p m8 -c avrisp2 -P usb -U flash:w:mega8motor_v2.hex`

**Comment by Springwald** [comment]
Hi Lambor,  thanks a lot - the motor driver works now perfect on i2c!
